* Standardized (z-transformed) Regression Based Change Scores
This R package allows you to calculate Standardized (z-transformed) Regression Based ('ZSRB') change scores. Such scores permit evaluation of meaningful changes in test scores over time, while accounting for test–retest reliability, practice effects, score fluctuations due to error, and relevant clinical and demographic factors.

Calculating ZSRB scores requires a control group that serves as the baseline population for estimating 'normal' expected change, and one or more other groups.

** Simple ZSRB
TBD

*** Input variables

*** Output variables

*** Example

** Complex ZSRB
TBD

*** Input variables

*** Output variables

*** Example


* Dependencies
This package does _not_ rely on other packages.

* Installation
** Make sure that devtools are installed so that you can install packages directly from github:
#+begin_src R
install.packages("devtools")
#+end_src

** Install the zsrb package using devtools
#+begin_src R
devtools::install_github("vnckppl/zsrb")
#+end_src
